const teamProject = [
    {
        name: "Focuse Frame",
        technologies: "HTML, CSS, JS, Vite",
        descriptionUA: "Веб-сайт розроблений для школи фотографії з адаптивним дизайном, бургер-меню, модальним вікном, формами та анімаціями.",
        descriptionEN: "The website is created for photography school with responsive design, burger menu, modal window, forms and animations.",
        projectEN: "Team project",
        projectUA: "Командний проєкт",
        urlOfSite: "https://maxdemo1.github.io/project_First_Flight/",
        urlOfGithub: "https://github.com/maxdemo1/project_First_Flight",
        imageBig: "",
        imageSmall: "",
    },
    {
        name: "Energy Flow",
        technologies: "HTML, CSS, JS, Vite",
        descriptionUA: "Веб-сайт розроблений для бажаючих мати гарну фізичну форму з адаптивним дизайном, мотивуючою цитатою дня, пошуком за ключовим словом, можливістю додати вправу до улюблених, модальними вікнами, формами та пагінацією.",
        descriptionEN: "The website is created for fitness enthusiasts with responsive design, motivational quote of the day, keyword search, option to add exercise to favorites, modal windows, forms and pagination.",
        projectEN: "Team project",
        projectUA: "Командний проєкт",
        urlOfSite: "https://karolinataran.github.io/project-dev-hunters/",
        urlOfGithub: "https://github.com/KarolinaTaran/project-dev-hunters",
        imageBig: "",
        imageSmall: "",
    },
]

const individualProject = [
    {
        name: "Timer",
        technologies: "HTML, CSS, JS, Vite",
        descriptionUA: "Застосунок розроблений для зворотного відліку часу до певної дати в майбутньому з використанням бібліотек Flatpickr та iziToast.",
        descriptionEN: "The application is created to count down the time to a certain date in the future using the Flatpickr and iziToast libraries.",
        projectEN: "Individual project",
        projectUA: "Індивідуальний проєкт",
        urlOfSite: "https://molchanovaolga.github.io/goit-js-hw-10/1-timer.html",
        urlOfGithub: "https://github.com/MolchanovaOlga/goit-js-hw-10/blob/main/src/js/1-timer.js",
        imageBig: "",
        imageSmall: "",
    },
    {
        name: "Gallery",
        technologies: "HTML, CSS, JS, Vite",
        descriptionUA: "Застосунок пошуку зображень за ключовим словом і їх перегляду в галереї з плавним прокручуванням сторінки.  Використано бібліотеки  Axios,  iziToast, css-loader, SimpleLightbox та АРІ сервіс Pixabay.",
        descriptionEN: "The application is created for searching images by keyword and viewing them in a gallery with smooth page scrolling. The libraries Axios, iziToast, css-loader, SimpleLightbox and the API service of Pixabay were used.",
        projectEN: "Individual project",
        projectUA: "Індивідуальний проєкт",
        urlOfSite: "https://molchanovaolga.github.io/goit-js-hw-12/",
        urlOfGithub: "https://github.com/MolchanovaOlga/goit-js-hw-12",
        imageBig: "",
        imageSmall: "",
    },
    {
        name: "WebStudio",
        technologies: "HTML, JS, SCSS, SASS",
        descriptionUA: "Cайт розроблений для компанії  “WebStudio”. Адаптивний дизайн, ефекти трансформації, модальні вікна.",
        descriptionEN: "The site is created for the company `WebStudio`. Adaptive design, transformation effects, modal windows.",
        projectEN: "Individual project",
        projectUA: "Індивідуальний проєкт",
        urlOfSite: "https://molchanovaolga.github.io/GoIt-markup-hw-8-uk/",
        urlOfGithub: "https://github.com/MolchanovaOlga/GoIt-markup-hw-8-uk",
        imageBig: "",
        imageSmall: "",
    },
]

export { teamProject, individualProject };